// Generated by tools/audio-manifest.mjs — do not edit. 8 pre-rendered lines.
/* eslint-disable @typescript-eslint/no-require-imports */
export const AUDIO: Record<string, number> = {
  "ob_age.mp3": require("../../assets/audio/ob_age.mp3"),
  "ob_bedtime.mp3": require("../../assets/audio/ob_bedtime.mp3"),
  "ob_goal.mp3": require("../../assets/audio/ob_goal.mp3"),
  "ob_name.mp3": require("../../assets/audio/ob_name.mp3"),
  "ob_people.mp3": require("../../assets/audio/ob_people.mp3"),
  "ob_plan.mp3": require("../../assets/audio/ob_plan.mp3"),
  "ob_tradition.mp3": require("../../assets/audio/ob_tradition.mp3"),
  "pw_hello.mp3": require("../../assets/audio/pw_hello.mp3"),
};
