import { z } from "zod";

export const NARRATIVE_ART_IDS = [
  "lost-sheep",
  "good-samaritan",
  "mustard-seed",
  "calm-storm",
  "loaves-fish",
  "zacchaeus",
  "jesus-children",
  "prodigal-son",
  "two-houses",
  "sower",
  "lost-sheep-flock",
  "lost-sheep-found",
  "good-samaritan-road",
  "good-samaritan-passing",
  "mustard-seed-tiny",
  "mustard-seed-birds",
  "calm-storm-waves",
  "calm-storm-wake",
  "loaves-fish-crowd",
  "loaves-fish-baskets",
  "zacchaeus-alone",
  "zacchaeus-sharing",
  "jesus-children-arriving",
  "jesus-children-waiting",
  "prodigal-son-leaving",
  "prodigal-son-hungry",
  "two-houses-building",
  "two-houses-rain",
  "sower-birds",
  "sower-weeds",
] as const;
export const NARRATIVE_SYMBOLS = [
  "heart",
  "hands",
  "people",
  "home",
  "sun",
  "moon",
  "ear",
  "leaf",
  "flower",
  "tree",
  "bird",
  "food",
  "water",
  "shield",
  "help",
  "forgive",
  "world",
  "road",
  "boat",
  "cloud",
  "seed",
  "rock",
  "sand",
  "basket",
  "coin",
  "sheep",
  "search",
  "book",
  "footsteps",
  "sad",
  "happy",
  "wheat",
] as const;

/** Stable visual ids travel with the content, independently of translated text. */
export const VisualCue = z.object({
  art: z.enum(NARRATIVE_ART_IDS).optional(),
  symbol: z.enum(NARRATIVE_SYMBOLS),
  motion: z.enum(["still", "glow", "float", "grow"]).default("glow"),
});
export type VisualCue = z.infer<typeof VisualCue>;
