// Parent-facing copy (not part of the kid pack). English only in v1; i18n key map for later packs.
export const P = {
  gate: {
    title: "Grown-ups only",
    hint: "Solve this, then press and hold the button.",
    hold: "Press and hold",
    holding: "Keep holding…",
    wrong: "Not quite. Try another one.",
  },
  onboarding: {
    title: "Let's set up Capy for your child",
    name: "What should Capy call your child?",
    namePlaceholder: "First name or nickname",
    age: "How old is your child?",
    tradition: "Your family's tradition",
    bedtime: "When is bedtime?",
    people: "Who should Capy help them pray for?",
    goal: "What matters most to you?",
    goals: ["A calm bedtime routine", "Learning to pray on their own", "Gratitude every day", "Praying for family"],
    next: "Next",
    finish: "Meet Capy",
    plan: (name: string) => `Capy's 4-week plan for ${name} is ready.`,
  },
  corner: {
    title: "Parent Corner",
    child: "Child",
    bedtime: "Bedtime",
    reminder: "Bedtime reminder (local notification)",
    people: "Prayer people",
    addPerson: "Add someone",
    note: "Note for Capy (e.g. \"Grandpa's surgery Tuesday\")",
    remove: "Remove",
    progress: "This week",
    voice: "Capy's voice: pre-rendered lines on this device",
    freePlay: "Free play (no daily limit)",
    freePlayHint: "Normally one Prayer Moment unlocks per day. Turn this on to try everything at once.",
    premium: "Premium (sandbox)",
    premiumHint: "Store purchases arrive with the RevenueCat build. This switch only simulates the entitlement.",
    deleteData: "Delete my child's data",
    deleteConfirm: "This erases the profile, progress, prayer people and streak on this device. Continue?",
    deleted: "Deleted.",
    privacy: "Capy Prayer collects no photos, voice, location or contacts. The only child data is a nickname, an age band and prayer progress, stored under your account.",
    backup: "Back up progress",
    backupHint: "Sign in with your email to keep progress safe and restore it on a new phone. We never ask for your child's data.",
    email: "Your email",
    sendCode: "Send code",
    code: "6-digit code",
    verify: "Sign in",
    signedIn: (email: string) => `Signed in as ${email}. Progress backs up automatically.`,
    signOut: "Sign out",
    restored: "Progress restored from your account.",
    offline: "Backup is off in this build (no server configured).",
    back: "Back to Capy",
    cancel: "Cancel",
    delete: "Delete",
  },
  paywall: {
    title: "Unlock the whole path",
    body: "Bedtime Prayer and Week 1 are free forever. Premium unlocks every week, the Pond rewards and up to 4 child profiles.",
    annual: "Annual · $49.99 ($4.17/mo · save 48%)",
    monthly: "Monthly · $7.99",
    trial: "7-day free trial",
    sandbox: "Continue in sandbox",
    restore: "Restore purchases",
    later: "Not now",
  },
  lock: "Premium",
} as const;
