import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFile, stat } from "node:fs/promises";
import { join, extname } from "node:path";
const dist = "/home/user/capypray/packages/avatar-web/dist";
const server = createServer(async (req, res) => { const p = join(dist, decodeURIComponent(new URL(req.url, "http://x").pathname)); try { await stat(p); res.writeHead(200, { "content-type": extname(p)===".html"?"text/html":extname(p)===".js"?"text/javascript":"application/octet-stream" }); res.end(await readFile(p)); } catch { res.writeHead(404).end(); } }).listen(0);
const port = server.address().port;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 480, height: 800 } });
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
page.on("console", (m) => m.type() === "error" && console.log("[console]", m.text().slice(0, 200)));
await page.goto(`http://localhost:${port}/preview.html?bare=1&clip=idle_breathe&gesture=wave_hello`);
await page.waitForFunction(() => window.__capyReady === true, null, { timeout: 60000 });
await page.waitForTimeout(900);
const info = await page.evaluate(() => {
  const { sm } = window.__capy;
  const g = [...sm.gestures.values()].map(a => ({ name: a.getClip().name, w: a.getEffectiveWeight(), t: a.time, running: a.isRunning(), enabled: a.enabled, bindings: a._propertyBindings.length, weightInterp: !!a._weightInterpolant }));
  const cur = sm.current?.getClip().name;
  return { g, cur, gesture: sm.gesture?.getClip().name };
});
console.log(JSON.stringify(info, null, 1));
await page.evaluate(() => window.__capy.sm.play("wave_hello", {}));
await page.waitForTimeout(500);
const info2 = await page.evaluate(() => { const sm = window.__capy.sm; const a = sm.gesture; return { cur: sm.current?.getClip().name, gesture: a ? { name: a.getClip().name, w: a.getEffectiveWeight(), t: a.time, running: a.isRunning() } : null }; });
console.log("after sm.play(wave_hello):", JSON.stringify(info2));
await page.evaluate(() => window.__capy.sm.play("idle_breathe", { loop: true }));
await page.waitForTimeout(300);
const info3 = await page.evaluate(() => { const sm = window.__capy.sm; const a = sm.gesture; return { cur: sm.current?.getClip().name, gesture: a ? { name: a.getClip().name, w: a.getEffectiveWeight(), t: a.time, running: a.isRunning() } : null }; });
console.log("after sm.play(idle_breathe):", JSON.stringify(info3));
await page.screenshot({ path: "/tmp/claude-0/-home-user-capypray/b4b1697b-c91a-5fb3-917a-910c0d840aa4/scratchpad/g_direct.png" });
await browser.close(); server.close();
