import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
const html = readFileSync(process.argv[2]);
const server = createServer((req, res) => { res.writeHead(200, { "content-type": "text/html" }); res.end(html); }).listen(0);
const port = server.address().port;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 400, height: 720 } });
const msgs = [];
await page.exposeFunction("__rn", (s) => msgs.push(s));
await page.addInitScript(() => { window.ReactNativeWebView = { postMessage: (s) => window.__rn(s) }; });
page.on("pageerror", (e) => console.log("[pageerror]", e.message.slice(0, 200)));
await page.goto(`http://localhost:${port}/`);
await page.waitForTimeout(6000);
await page.evaluate(() => window.capy && window.capy.send({ type: "speak", durationMs: 3000 }));
await page.waitForTimeout(1500);
console.log("messages:", msgs.map((m) => m.slice(0, 80)));
await page.screenshot({ path: process.argv[3] });
await browser.close(); server.close();
