// Mirror of packages/content AVATAR_CLIPS (avatar-web must not depend on node-only packages).
export const AVATAR_CLIPS = [
  "idle_breathe",
  "idle_look",
  "wave_hello",
  "talk_a",
  "talk_b",
  "listen_nod",
  "pray_hands",
  "kneel_pray",
  "celebrate",
  "clap",
  "heart",
  "think",
  "yawn",
  "sleep",
  "chill_lie",
  "munch",
  "rise",
  "to_sleep",
  "wake",
  "sad",
  "walk",
] as const;
