const {createRequire}=require('node:module');
const path=require('node:path');
const {chromium}=createRequire(path.resolve(__dirname,'../packages/avatar-web/package.json'))('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const pack=require('../packages/content/packs/christian-us-en-v1/pack.json');
(async()=>{
 const out=process.env.CAPY_SCREENSHOTS||path.resolve(__dirname,'../test-results/breathing');fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM||undefined,headless:true,args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
 try {
  const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  const copy=pack.companion.breathing;
  await page.goto('http://127.0.0.1:8081/places');
  const scene=pack.scenes.find(s=>s.id==='pond');await page.getByText(scene.title,{exact:true}).click();
  await page.getByText(pack.ui.next,{exact:true}).click();
  const prayer=pack.prayers.find(p=>p.id===scene.prayerId); if(prayer) for(const _ of prayer.lines) await page.getByText(pack.ui.iSaidIt,{exact:true}).click();
  await page.getByText(copy.title,{exact:true}).waitFor();
  assert.equal(await page.getByText(pack.ui.nudgeRepeat,{exact:true}).count(),0);
  await page.frameLocator('iframe').locator('canvas').waitFor();await page.waitForTimeout(800);
  await page.screenshot({path:path.join(out,'breathing-ready.png')});
  await page.getByRole('button',{name:copy.start,exact:true}).click();
  await page.getByText(pack.companion.ui.breatheOut,{exact:true}).waitFor({timeout:6000});
  await page.screenshot({path:path.join(out,'breathing-active.png')});
  await page.getByRole('button',{name:copy.pause,exact:true}).click();
  await page.getByText(copy.paused,{exact:true}).waitFor();
  await page.waitForTimeout(150);
  const before=await page.getByTestId('breathing-glow').evaluate(e=>getComputedStyle(e).transform);
  await page.waitForTimeout(1000);
  assert.equal(await page.getByTestId('breathing-glow').evaluate(e=>getComputedStyle(e).transform),before);
  await page.getByRole('button',{name:copy.resume,exact:true}).click();
  await page.getByText(copy.complete,{exact:true}).waitFor({timeout:18000});
  assert.ok(page.url().endsWith('/place/pond'));
  await page.screenshot({path:path.join(out,'breathing-complete.png')});
  await page.getByRole('button',{name:copy.continue,exact:true}).click();
  await page.waitForURL('**/places');
  await page.setViewportSize({width:320,height:568});await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto('http://127.0.0.1:8081/lesson/moment-worried');await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByRole('button',{name:copy.start,exact:true}).click();
  const still=await page.getByTestId('breathing-glow').evaluate(e=>getComputedStyle(e).transform);
  await page.getByText(pack.companion.ui.breatheOut,{exact:true}).waitFor({timeout:6000});
  assert.equal(await page.getByTestId('breathing-glow').evaluate(e=>getComputedStyle(e).transform),still);
  await page.screenshot({path:path.join(out,'breathing-small-reduced-motion.png')});
  const box=await page.getByRole('button',{name:copy.finish,exact:true}).boundingBox();assert.ok(box && box.y+box.height<=570);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:copy.finish,exact:true}).click();
  await page.getByText(pack.ui.iSaidIt,{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('Passed: correct place instructions, full breathing cycles, pause/resume, explicit completion, early finish, and 320px reduced motion.');
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
