const { createRequire } = require('node:module');
const { chromium } = createRequire(require('node:path').resolve(__dirname, '../packages/avatar-web/package.json'))('playwright');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const output = process.env.CAPY_SCREENSHOTS || path.resolve(__dirname, '../test-results');
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM || undefined, headless: true, args: ['--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  const errors = [];
  const shot = async (name) => {
    const frame = page.frameLocator('iframe');
    await frame.locator('canvas').waitFor({ timeout:30000 });
    await page.waitForTimeout(750);
    await page.screenshot({path:path.join(output,name)});
  };
  page.on('pageerror', error => errors.push(String(error)));
  await page.goto('http://127.0.0.1:8081');
  await page.getByText('Meet your prayer buddy.', { exact: true }).waitFor({timeout:30000});
  await page.waitForTimeout(2200);
  await shot('01-welcome.png');
  await page.getByRole('button', {name:'Meet Capy',exact:true}).click();
  await page.getByRole('textbox').fill('Mia');
  await page.getByRole('button', {name:'Continue',exact:true}).click();
  await page.getByRole('radio', {name:'8:00 PM',exact:true}).click();
  await shot('02-rhythm.png');
  await page.getByRole('button', {name:'Continue',exact:true}).click();
  await page.getByRole('button', {name:"Let's pray together",exact:true}).click();
  const pack = require('../packages/content/packs/christian-us-en-v1/pack.json');
  for(let i=0;i<2;i++) await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByText('Hi God, it’s me, Mia.',{exact:true}).waitFor();
  await shot('03-first-prayer.png');
  for(let i=0;i<3;i++) await page.getByText(pack.ui.iSaidIt,{exact:true}).click();
  await page.getByText(pack.ui.yay,{exact:true}).click();
  await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByText('How is your heart today?',{exact:true}).waitFor();
  await page.waitForTimeout(600);
  await shot('04-home.png');
  await page.reload();
  await page.getByText('Hi, Mia.',{exact:true}).waitFor();
  await page.getByText('Worried',{exact:true}).click();
  await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByText('Breathe gently. God is here with us.',{exact:true}).waitFor();
  await shot('05-breathe.png');
  await page.getByRole('button', { name: pack.companion.breathing.start, exact: true }).click();
  await page.getByRole('button', { name: pack.companion.breathing.continue, exact: true }).click({ timeout: 22000 });
  await page.getByText(pack.ui.iSaidIt,{exact:true}).waitFor({timeout:22000});
  for(let i=0;i<3;i++) await page.getByText(pack.ui.iSaidIt,{exact:true}).click();
  await page.getByText(pack.ui.yay,{exact:true}).click();
  await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByText('How is your heart today?',{exact:true}).waitFor();
  await page.goto('http://127.0.0.1:8081/stories');
  await page.getByText('The Lost Sheep',{exact:true}).click();
  await page.getByText(pack.ui.next,{exact:true}).click();
  await page.getByText(pack.stories.find(s=>s.id==='lost-sheep').pages[0].text,{exact:true}).waitFor();
  await shot('06-story.png');
  await page.goto('http://127.0.0.1:8081/moments');
  await page.getByText('Little prayers, big feelings.',{exact:true}).waitFor();
  await page.waitForTimeout(650);
  await page.screenshot({path:path.join(output,'07-moments.png')});
  await page.goto('http://127.0.0.1:8081/journey');
  await page.getByText('Your prayer path',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'08-journey.png')});
  await page.goto('http://127.0.0.1:8081/lesson/moment-sleepy');
  await page.getByText('Let’s put the busy day down for a little while.',{exact:true}).waitFor();
  await shot('10-bedtime.png');
  await page.goto('http://127.0.0.1:8081/');
  await page.setViewportSize({width:1440,height:1000});
  await page.getByText('How is your heart today?',{exact:true}).waitFor();
  await shot('11-desktop.png');
  const small = await browser.newPage({viewport:{width:320,height:568},reducedMotion:'reduce'});
  await small.goto('http://127.0.0.1:8081');
  await small.getByRole('button',{name:'Meet Capy',exact:true}).waitFor();
  await small.frameLocator('iframe').locator('canvas').waitFor();
  await small.waitForTimeout(750);
  await small.screenshot({path:path.join(output,'09-small-screen.png')});
  await small.getByRole('button',{name:'Meet Capy',exact:true}).click();
  await small.getByRole('button',{name:'Continue',exact:true}).click();
  await small.getByRole('button',{name:'Continue',exact:true}).click();
  await small.getByRole('button',{name:"Let's pray together",exact:true}).click();
  await small.getByText('Hi, friend! I’m Capy. I’m glad you’re here.',{exact:true}).waitFor();
  console.log('PASS: onboarding, optional nickname, first prayer, home, reload persistence, emotional moment, story pages, library, journey, 320px screen, reduced motion.');
  console.log('PAGE ERRORS', errors);
  if(errors.length) throw new Error('Browser exceptions occurred');
  await browser.close();
})().catch(error => {console.error(error);process.exit(1);});
